# Generated by Django 4.2.7 on 2024-06-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=31, unique=True)),
                ("email", models.CharField(max_length=63, unique=True)),
                ("password", models.CharField(max_length=31)),
            ],
        ),
    ]
